### ISSUE TITLE
Using OISD with other blocklists?

### ISSUE THREAD

**Issue by gaborho** [yokoffing/NextDNS-Config#19]
Hi, thank you for your excellent guide. I'd like to ask your opinion about using OISD alone vs. OISD + 1Host (lite) as you suggested in Balanced. Please check the argumentation of one reddit user here, who thinks OISD alone is preferred: https://www.reddit.com/r/nextdns/comments/uxl2jm/using_oisd_with_other_blocklists/
I appreciate if you would share your thoughts about this with us and give guidance. Thank you.

**Comment by yokoffing** [comment]
Short answer: Choose what you're comfortable with.

A bit longer answer: If you're new to this space, you may not know that this discussion has been rehashed to death. It's everywhere on NextDNS subreddit posts. I'll summarize here:

- OISD has false positives, too. [I reported one to the maintainer just yesterday](https://old.reddit.com/r/oisd_blocklist/comments/s70dhx/oisd_domain_blocklist/j3cqmkg/?context=3).
- 99% of the time, you'll not see any breakage using one or both 1Host Lite and OISD, which is why they're in the Balanced section. They are true to my definitions laid out in the guide. Which brings up another point:
- The blocklist recommendations on this guide are not chosen lightly. I give suggestions based on numerous hours of testing and comparison of real-world use, family member feedback, documentation (all the footnotes), and yes Reddit users.
- OISD is great but it allows for too much on its own. It works well with a list that is slightly stricter but not too much, which is where 1Host Lite fits the bill; it's unique in that regard.
- 1Host Lite blocks a few requests that OISD doesn't cover, and vice versa.

Cheers

**Comment by gaborho** [comment]
Great, thanks for the detailed explanation. Yes, I'm new to this space. Your guide really helped a lot. I was just concerned because of the reddit post I linked above. I wanted to avoid the situation where I block something with one list, and then allow with another. Cheers.
